name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

      # - uses: actions/checkout@v3
      # - uses: fregante/setup-git-user@v1
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: npm install --legacy-peer-deps
      # - run: npm run deploy